apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    {{- include "paralegalai.labels" . | nindent 4 }}
  name: {{ include "paralegalai.fullname" . }}-config
data:
{{- range $key, $value := .Values.config }}
  {{ $key }}: "{{ $value }}"
{{- end }}